
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    dashboard: "Painel",
    reports: "Relatórios",
    about: "Sobre",
    welcome: "Bem-vindo ao Info SP",
    subtitle: "Sistema de Visualização de Ocorrências de Segurança Pública",
    description: "Dados de criminalidade e segurança pública do estado de São Paulo, com visualizações interativas e análises em tempo real.",
    occurrencesByType: "Ocorrências por Tipo",
    occurrencesByLevel: "Distribuição por Nível",
    geographicDistribution: "Distribuição Geográfica",
    recentOccurrences: "Ocorrências Recentes",
    viewDetails: "Ver Detalhes",
    total: "Total",
    thisMonth: "Este Mês",
    high: "Alta",
    medium: "Média",
    low: "Baixa",
    critical: "Crítica",
    theft: "Furto",
    robbery: "Roubo",
    rape: "Estupro",
    homicide: "Homicídio",
    byType: "Por Tipo",
    byLevel: "Por Nível",
    topCities: "Top 10 Cidades com Mais Ocorrências",
    level: "Nível",
    city: "Cidade",
    occurrences: "Ocorrências",
    accessAndExport: "Acesse e exporte relatórios do sistema",
    downloadSpreadsheet: "Baixar Planilha",
    availableReports: "Relatórios Disponíveis",
    accessSystemReports: "Acesse relatórios gerados pelo sistema",
    reportID: "ID do Relatório",
    reportTitle: "Título do Relatório",
    reportDate: "Data do Relatório",
    reportType: "Tipo do Relatório",
    reportStatus: "Status do Relatório",
    reportAction: "Ação do Relatório",
    monthlyAnalysis: "Análise mensal de ocorrências",
    monthly: "Mensal",
    available: "Disponível",
    download: "Baixar",
    downloadStarted: "Download iniciado com sucesso!",
    projectDescription: "Este projeto apresenta dados de criminalidade e segurança pública do estado de São Paulo através de visualizações interativas e análises detalhadas.",
    aboutProject: "Sobre o Projeto",
    dataSource: "Fonte dos Dados",
    dataSourceDescription: "Os dados utilizados neste sistema são baseados em registros oficiais de ocorrências policiais, processados e organizados para facilitar a análise e compreensão dos padrões criminais.",
    mainFeatures: "Principais Funcionalidades",
    interactiveCharts: "Gráficos Interativos",
    interactiveChartsDesc: "Visualize dados através de gráficos de barras, linhas e pizza com informações detalhadas.",
    geographicAnalysis: "Análise Geográfica",
    geographicAnalysisDesc: "Explore a distribuição de crimes por regiões e cidades do estado.",
    detailedReports: "Relatórios Detalhados",
    detailedReportsDesc: "Acesse relatórios completos com análises aprofundadas dos dados.",
    exportData: "Exportação de Dados",
    exportDataDesc: "Baixe planilhas com os dados para suas próprias análises.",
    safetyTip: "Dica de Segurança",
    emergencyContacts: "Contatos de Emergência",
    securityTip1: "Mantenha sempre seus documentos em local seguro",
    securityTip2: "Evite demonstrar objetos de valor em público",
    securityTip3: "Esteja atento ao seu entorno, principalmente à noite",
    securityTip4: "Use transporte público com cautela em horários de pico",
    securityTip5: "Tenha sempre os contatos de emergência à mão",
    completeDetails: "Detalhes completos desta ocorrência",
    totalRecorded: "Total Registrado",
    totalIn2024: "Total em 2024",
    growthBetweenYears: "Crescimento 2023-2024",
    top5Cities: "Top 5 Cidades",
    growthByYear: "Crescimento por Ano",
    year: "Ano",
    totalOccurrences: "Total de Ocorrências",
    cityNotFound: "Cidade Não Encontrada",
    noDataAvailableCity: "Não há dados disponíveis para esta cidade.",
    back: "Voltar",
    cityDetails: "Detalhes da Cidade",
    recordedCrimes: "Crimes registrados por ano",
    bars: "Barras",
    lines: "Linhas",
    pie: "Pizza",
    in2024: "em 2024",
    regionNotFound: "Região Não Encontrada",
    noDataAvailableRegion: "Não há dados disponíveis para esta região.",
    regionDetails: "Detalhes da Região",
    crimesInRegion: "Crimes registrados na região por ano",
    expandedView: "Visualização Expandida",
    clickToExpand: "Clique para expandir",
    allRights: "Todos os direitos reservados",
    contact: "Contato",
    privacy: "Privacidade",
    terms: "Termos",
    mostRecurringOccurrences: "Tipos de Ocorrências Mais Recorrentes",
    mostFrequentTypes: "Os tipos de ocorrências mais frequentes no sistema",
    typeId: "ID do Tipo",
    filterByLevel: "Filtrar por Nível",
    filter: "Filtrar",
    vehicleTheft: "Furto de Veículo",
    streetLightingIssue: "Problema de Iluminação Pública",
    trafficAccident: "Acidente de Trânsito",
    propertyInvasion: "Invasão de Propriedade",
    publicPropertyVandalism: "Vandalismo ao Patrimônio Público",
    referenceCode: "Código de referência",
    occurrencePercentage: "Esta ocorrência representa",
    ofTotalRecorded: "do total registrado",
    showingOf: "Mostrando",
    of: "de",
    viewAll: "Ver Todos"
  },
  en: {
    dashboard: "Dashboard",
    reports: "Reports",
    about: "About",
    welcome: "Welcome to Info SP",
    subtitle: "Public Safety Occurrence Visualization System",
    description: "Crime and public safety data from São Paulo state, with interactive visualizations and real-time analysis.",
    occurrencesByType: "Occurrences by Type",
    occurrencesByLevel: "Distribution by Level",
    geographicDistribution: "Geographic Distribution",
    recentOccurrences: "Recent Occurrences",
    viewDetails: "View Details",
    total: "Total",
    thisMonth: "This Month",
    high: "High",
    medium: "Medium",
    low: "Low",
    critical: "Critical",
    theft: "Theft",
    robbery: "Robbery",
    rape: "Rape",
    homicide: "Homicide",
    byType: "By Type",
    byLevel: "By Level",
    topCities: "Top 10 Cities with Most Occurrences",
    level: "Level",
    city: "City",
    occurrences: "Occurrences",
    accessAndExport: "Access and export system reports",
    downloadSpreadsheet: "Download Spreadsheet",
    availableReports: "Available Reports",
    accessSystemReports: "Access reports generated by the system",
    reportID: "Report ID",
    reportTitle: "Report Title",
    reportDate: "Report Date",
    reportType: "Report Type",
    reportStatus: "Report Status",
    reportAction: "Report Action",
    monthlyAnalysis: "Monthly occurrence analysis",
    monthly: "Monthly",
    available: "Available",
    download: "Download",
    downloadStarted: "Download started successfully!",
    projectDescription: "This project presents crime and public safety data from São Paulo state through interactive visualizations and detailed analysis.",
    aboutProject: "About the Project",
    dataSource: "Data Source",
    dataSourceDescription: "The data used in this system is based on official police occurrence records, processed and organized to facilitate analysis and understanding of crime patterns.",
    mainFeatures: "Main Features",
    interactiveCharts: "Interactive Charts",
    interactiveChartsDesc: "View data through bar, line and pie charts with detailed information.",
    geographicAnalysis: "Geographic Analysis",
    geographicAnalysisDesc: "Explore crime distribution by regions and cities in the state.",
    detailedReports: "Detailed Reports",
    detailedReportsDesc: "Access complete reports with in-depth data analysis.",
    exportData: "Data Export",
    exportDataDesc: "Download spreadsheets with data for your own analysis.",
    safetyTip: "Safety Tip",
    emergencyContacts: "Emergency Contacts",
    securityTip1: "Always keep your documents in a safe place",
    securityTip2: "Avoid displaying valuable objects in public",
    securityTip3: "Stay alert to your surroundings, especially at night",
    securityTip4: "Use public transport with caution during peak hours",
    securityTip5: "Always have emergency contacts at hand",
    completeDetails: "Complete details of this occurrence",
    totalRecorded: "Total Recorded",
    totalIn2024: "Total in 2024",
    growthBetweenYears: "Growth 2023-2024",
    top5Cities: "Top 5 Cities",
    growthByYear: "Growth by Year",
    year: "Year",
    totalOccurrences: "Total Occurrences",
    cityNotFound: "City Not Found",
    noDataAvailableCity: "No data available for this city.",
    back: "Back",
    cityDetails: "City Details",
    recordedCrimes: "Crimes recorded per year",
    bars: "Bars",
    lines: "Lines",
    pie: "Pie",
    in2024: "in 2024",
    regionNotFound: "Region Not Found",
    noDataAvailableRegion: "No data available for this region.",
    regionDetails: "Region Details",
    crimesInRegion: "Crimes recorded in the region per year",
    expandedView: "Expanded View",
    clickToExpand: "Click to expand",
    allRights: "All rights reserved",
    contact: "Contact",
    privacy: "Privacy",
    terms: "Terms",
    mostRecurringOccurrences: "Most Recurring Occurrence Types",
    mostFrequentTypes: "The most frequent types of occurrences in the system",
    typeId: "Type ID",
    filterByLevel: "Filter by Level",
    filter: "Filter",
    vehicleTheft: "Vehicle Theft",
    streetLightingIssue: "Street Lighting Issue",
    trafficAccident: "Traffic Accident",
    propertyInvasion: "Property Invasion",
    publicPropertyVandalism: "Public Property Vandalism",
    referenceCode: "Reference code",
    occurrencePercentage: "This occurrence represents",
    ofTotalRecorded: "of total recorded",
    showingOf: "Showing",
    of: "of",
    viewAll: "View All"
  },
  es: {
    dashboard: "Panel",
    reports: "Informes",
    about: "Acerca de",
    welcome: "Bienvenido a Info SP",
    subtitle: "Sistema de Visualización de Ocurrencias de Seguridad Pública",
    description: "Datos de criminalidad y seguridad pública del estado de São Paulo, con visualizaciones interactivas y análisis en tiempo real.",
    occurrencesByType: "Ocurrencias por Tipo",
    occurrencesByLevel: "Distribución por Nivel",
    geographicDistribution: "Distribución Geográfica",
    recentOccurrences: "Ocurrencias Recientes",
    viewDetails: "Ver Detalles",
    total: "Total",
    thisMonth: "Este Mes",
    high: "Alta",
    medium: "Media",
    low: "Baja",
    critical: "Crítica",
    theft: "Hurto",
    robbery: "Robo",
    rape: "Violación",
    homicide: "Asesinato",
    byType: "Por Tipo",
    byLevel: "Por Nivel",
    topCities: "Top 10 Ciudades con Más Ocurrencias",
    level: "Nivel",
    city: "Ciudad",
    occurrences: "Ocurrencias",
    accessAndExport: "Accede y exporta informes del sistema",
    downloadSpreadsheet: "Descargar Hoja de Cálculo",
    availableReports: "Informes Disponibles",
    accessSystemReports: "Accede a informes generados por el sistema",
    reportID: "ID del Informe",
    reportTitle: "Título del Informe",
    reportDate: "Fecha del Informe",
    reportType: "Tipo de Informe",
    reportStatus: "Estado del Informe",
    reportAction: "Acción del Informe",
    monthlyAnalysis: "Análisis mensual de ocurrencias",
    monthly: "Mensual",
    available: "Disponible",
    download: "Descargar",
    downloadStarted: "¡Descarga iniciada con éxito!",
    projectDescription: "Este proyecto presenta datos de criminalidad y seguridad pública del estado de São Paulo a través de visualizaciones interactivas y análisis detallado.",
    aboutProject: "Sobre el Proyecto",
    dataSource: "Fuente de Datos",
    dataSourceDescription: "Los datos utilizados en este sistema se basan en registros oficiales de ocurrencias policiales, procesados y organizados para facilitar el análisis y comprensión de patrones criminales.",
    mainFeatures: "Características Principales",
    interactiveCharts: "Gráficos Interactivos",
    interactiveChartsDesc: "Visualiza datos a través de gráficos de barras, líneas y pastel con información detallada.",
    geographicAnalysis: "Análisis Geográfico",
    geographicAnalysisDesc: "Explora la distribución de crímenes por regiones y ciudades del estado.",
    detailedReports: "Informes Detallados",
    detailedReportsDesc: "Accede a informes completos con análisis profundo de los datos.",
    exportData: "Exportación de Datos",
    exportDataDesc: "Descarga hojas de cálculo con los datos para tus propios análisis.",
    safetyTip: "Consejo de Seguridad",
    emergencyContacts: "Contactos de Emergencia",
    securityTip1: "Mantén siempre tus documentos en lugar seguro",
    securityTip2: "Evita mostrar objetos de valor en público",
    securityTip3: "Mantente alerta a tu entorno, especialmente por la noche",
    securityTip4: "Usa el transporte público con precaución en horas pico",
    securityTip5: "Mantén siempre los contactos de emergencia a mano",
    completeDetails: "Detalles completos de esta ocurrencia",
    totalRecorded: "Total Registrado",
    totalIn2024: "Total en 2024",
    growthBetweenYears: "Crecimiento 2023-2024",
    top5Cities: "Top 5 Ciudades",
    growthByYear: "Crecimiento por Año",
    year: "Año",
    totalOccurrences: "Total de Ocurrencias",
    cityNotFound: "Ciudad No Encontrada",
    noDataAvailableCity: "No hay datos disponibles para esta ciudad.",
    back: "Volver",
    cityDetails: "Detalles de la Ciudad",
    recordedCrimes: "Crímenes registrados por año",
    bars: "Barras",
    lines: "Líneas",
    pie: "Pastel",
    in2024: "en 2024",
    regionNotFound: "Región No Encontrada",
    noDataAvailableRegion: "No hay datos disponibles para esta región.",
    regionDetails: "Detalles de la Región",
    crimesInRegion: "Crímenes registrados en la región por año",
    expandedView: "Vista Expandida",
    clickToExpand: "Haz clic para expandir",
    allRights: "Todos los derechos reservados",
    contact: "Contacto",
    privacy: "Privacidad",
    terms: "Términos",
    mostRecurringOccurrences: "Tipos de Ocurrencias Más Recurrentes",
    mostFrequentTypes: "Los tipos de ocurrencias más frecuentes en el sistema",
    typeId: "ID del Tipo",
    filterByLevel: "Filtrar por Nivel",
    filter: "Filtrar",
    vehicleTheft: "Robo de Vehículo",
    streetLightingIssue: "Problema de Alumbrado Público",
    trafficAccident: "Accidente de Tráfico",
    propertyInvasion: "Invasión de Propiedad",
    publicPropertyVandalism: "Vandalismo al Patrimonio Público",
    referenceCode: "Código de referencia",
    occurrencePercentage: "Esta ocurrencia representa",
    ofTotalRecorded: "del total registrado",
    showingOf: "Mostrando",
    of: "de",
    viewAll: "Ver Todos"
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<string>('pt');

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
