
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  pt: {
    dashboard: "Painel de Controle",
    reports: "Relatórios",
    regionalData: "Dados Regionais",
    about: "Sobre",
    showingOf: "Mostrando",
    of: "de",
    occurrences: "ocorrências",
    viewAll: "Ver Todos",
    typeId: "ID do Tipo",
    description: "Descrição",
    level: "Nível",
    totalOccurrences: "Total de Ocorrências",
    mostRecurringOccurrences: "Ocorrências Mais Recorrentes",
    mostFrequentTypes: "Tipos mais frequentes de ocorrências",
    filter: "Filtrar",
    filterByLevel: "Filtrar por Nível",
    critical: "Crítica",
    high: "Alta",
    medium: "Média",
    low: "Baixa",
    referenceCode: "Código de Referência",
    occurrencePercentage: "Esta ocorrência representa",
    ofTotalRecorded: "do total registrado",
    downloadSpreadsheet: "Baixar Planilha",
    accessAndExport: "Acesse e exporte os dados do sistema",
    availableReports: "Relatórios Disponíveis",
    accessSystemReports: "Acesse os relatórios gerados pelo sistema",
    reportID: "ID do Relatório",
    reportTitle: "Título do Relatório",
    reportDate: "Data do Relatório",
    reportType: "Tipo de Relatório",
    reportStatus: "Status do Relatório",
    reportAction: "Ação",
    monthlyAnalysis: "Análise Mensal de Ocorrências",
    monthly: "Mensal",
    available: "Disponível",
    download: "Baixar",
    downloadStarted: "Download iniciado!",
    allOccurrences: "Todas as Ocorrências",
    completeOccurrencesList: "Lista completa de todos os tipos de ocorrências registradas no sistema",
    backToDashboard: "Voltar ao Dashboard",
    dataTable: "Tabela de Dados",
    charts: "Gráficos",
    allOccurrenceTypes: "Todos os Tipos de Ocorrências",
    detailedOccurrenceData: "Dados detalhados de ocorrências por ano e tipo",
    distributionChart: "Gráfico de Distribuição",
    evolutionChart: "Gráfico de Evolução",
    occurrenceDistribution: "Distribuição de Ocorrências",
    distributionByType: "Distribuição percentual por tipo de ocorrência",
    yearlyEvolution: "Evolução Anual",
    evolutionOverYears: "Evolução das ocorrências ao longo dos anos",
    completeDetails: "Detalhes Completos",
    viewCompleteDetails: "Ver Detalhes Completos",
    numberOfThefts: "Número de Furtos",
    theft: "Furto",
    numberOfRobberies: "Número de Roubos",
    robbery: "Roubo",
    dangerousCity: "Cidade Perigosa",
    safeCity: "Cidade Segura",
    dangerousRegion: "Região Perigosa",
    safeRegion: "Região Segura",
    distribution: "Distribuição",
    byRegion: "Por Região",
    bytype: "Por Tipo",
    top10Cities: "Top 10 Cidades",
    top10CitiesTooltip: "As 10 cidades com mais ocorrências",
    intentionalHomicide: "Homicídio Doloso",
    intentionalHomicideVictims: "Vítimas de Homicídio Doloso",
    trafficIntentionalHomicide: "Homicídio Doloso no Trânsito",
    trafficIntentionalHomicideVictims: "Vítimas de Homicídio Doloso no Trânsito",
    trafficNegligentHomicide: "Homicídio Culposo no Trânsito",
    otherNegligentHomicide: "Outros Homicídios Culposos",
    attemptedHomicide: "Tentativa de Homicídio",
    bodilyInjuryWithDeath: "Lesão Corporal Seguida de Morte",
    intentionalBodilyInjury: "Lesão Corporal Dolosa",
    trafficNegligentInjury: "Lesão Corporal Culposa no Trânsito",
    crimeEvolutionByYear: "Evolução do Crime por Ano",
    crimeEvolutionTooltip: "Evolução temporal dos crimes registrados",
    totalOf: "Total de",
    totalOccurrencesLastYears: "Total de Ocorrências dos Últimos Anos",
    yearlyRecords: "Registros Anuais",
    totalOccurrencesTooltip: "Total acumulado de ocorrências",
    distributionTooltip: "Distribuição por categoria",
    localityData: "Dados por Localidade",
    localityDataDescription: "Análise detalhada das ocorrências por cidade e região",
    searchCityRegion: "Buscar cidade ou região",
    byCity: "Por Cidade",
    region: "Região",
    occurrencesIn2024: "Ocorrências em 2024",
    population: "População",
    cityDetails: "Detalhes da Cidade",
    recordedCrimes: "Crimes Registrados",
    bars: "Barras",
    lines: "Linhas",
    pie: "Pizza",
    rape: "Estupro",
    homicide: "Homicídio",
    regionDetails: "Detalhes da Região",
    regionRepresents: "A região representa",
    representsPercentage: "representa",
    ofTotalOccurrences: "do total de ocorrências",
    withTotal: "com total de",
    recordsIn2024: "registros em 2024",
    cities: "cidades",
    crimesByYear: "Crimes por Ano",
    back: "Voltar",
    projectInfoSP: "Projeto Info SP",
    mappingAndAnalysis: "Mapeamento e análise inteligente de ocorrências em São Paulo",
    generalObjective: "Objetivo Geral",
    generalObjectiveDesc: "Desenvolver uma plataforma inteligente para monitoramento e análise de dados de segurança pública",
    technologiesAndFeatures: "Tecnologias e Funcionalidades",
    geolocation: "Geolocalização avançada",
    interactiveDashboards: "Dashboards interativos",
    temporalAnalysis: "Análise temporal",
    predictiveAlgorithms: "Algoritmos preditivos",
    responsiveDesign: "Design responsivo",
    specificObjectives: "Objetivos Específicos",
    collectData: "Coletar dados de segurança",
    buildInterface: "Construir interface intuitiva",
    implementFilters: "Implementar filtros avançados",
    applyVisualization: "Aplicar técnicas de visualização",
    usePredictive: "Usar algoritmos preditivos",
    projectTeam: "Equipe do Projeto",
    teamDescription: "Projeto desenvolvido por estudantes de Engenharia de Software",
    advisor: "Orientador",
    developmentTeam: "Equipe de Desenvolvimento",
    semester: "Semestre",
    semesterValue: "2024/2",
    conclusion: "Conclusão",
    conclusionText: "O Info SP representa uma solução inovadora para análise de dados de segurança pública, oferecendo insights valiosos para tomada de decisões estratégicas.",
    allDataFrom: "Todos os dados são provenientes da",
    securityDepartment: "Secretaria de Segurança Pública",
    copyright: "© 2024 Info SP. Todos os direitos reservados.",
    portuguese: "Português",
    english: "Inglês",
    spanish: "Espanhol",
    // Tipos de ocorrências
    vehicleTheft: "Furto de Veículo",
    streetLightingIssue: "Problema de Iluminação Pública",
    trafficAccident: "Acidente de Trânsito",
    propertyInvasion: "Invasão de Propriedade",
    publicPropertyVandalism: "Vandalismo em Propriedade Pública",
    domesticViolence: "Violência Doméstica",
    drugTrafficking: "Tráfico de Drogas",
    noisePollution: "Poluição Sonora",
    publicPropertyDamage: "Dano ao Patrimônio Público",
    fraudAndScam: "Fraude e Golpe",
    illegalConstruction: "Construção Ilegal",
    waterLeakage: "Vazamento de Água",
    animalAbuse: "Maus-tratos a Animais",
    environmentalViolation: "Violação Ambiental",
    publicTransportIssue: "Problema no Transporte Público",
    roadDamage: "Dano na Via Pública",
    garbageIssue: "Problema com Lixo",
    sewerIssue: "Problema no Esgoto",
    publicSpaceOccupation: "Ocupação Irregular do Espaço Público",
    powerOutage: "Falta de Energia",
    internetOutage: "Falta de Internet",
    publicHealthIssue: "Problema de Saúde Pública",
    educationIssue: "Problema na Educação",
    total: "Total"
  },
  en: {
    dashboard: "Dashboard",
    reports: "Reports",
    regionalData: "Regional Data",
    about: "About",
    showingOf: "Showing",
    of: "of",
    occurrences: "occurrences",
    viewAll: "View All",
    typeId: "Type ID",
    description: "Description",
    level: "Level",
    totalOccurrences: "Total Occurrences",
    mostRecurringOccurrences: "Most Recurring Occurrences",
    mostFrequentTypes: "Most frequent types of occurrences",
    filter: "Filter",
    filterByLevel: "Filter by Level",
    critical: "Critical",
    high: "High",
    medium: "Medium",
    low: "Low",
    referenceCode: "Reference Code",
    occurrencePercentage: "This occurrence represents",
    ofTotalRecorded: "of the total recorded",
    downloadSpreadsheet: "Download Spreadsheet",
    accessAndExport: "Access and export system data",
    availableReports: "Available Reports",
    accessSystemReports: "Access system-generated reports",
    reportID: "Report ID",
    reportTitle: "Report Title",
    reportDate: "Report Date",
    reportType: "Report Type",
    reportStatus: "Report Status",
    reportAction: "Action",
    monthlyAnalysis: "Monthly Occurrence Analysis",
    monthly: "Monthly",
    available: "Available",
    download: "Download",
    downloadStarted: "Download started!",
    allOccurrences: "All Occurrences",
    completeOccurrencesList: "Complete list of all occurrence types recorded in the system",
    backToDashboard: "Back to Dashboard",
    dataTable: "Data Table",
    charts: "Charts",
    allOccurrenceTypes: "All Occurrence Types",
    detailedOccurrenceData: "Detailed occurrence data by year and type",
    distributionChart: "Distribution Chart",
    evolutionChart: "Evolution Chart",
    occurrenceDistribution: "Occurrence Distribution",
    distributionByType: "Percentage distribution by occurrence type",
    yearlyEvolution: "Yearly Evolution",
    evolutionOverYears: "Evolution of occurrences over the years",
    completeDetails: "Complete Details",
    viewCompleteDetails: "View Complete Details",
    numberOfThefts: "Number of Thefts",
    theft: "Theft",
    numberOfRobberies: "Number of Robberies",
    robbery: "Robbery",
    dangerousCity: "Dangerous City",
    safeCity: "Safe City",
    dangerousRegion: "Dangerous Region",
    safeRegion: "Safe Region",
    distribution: "Distribution",
    byRegion: "By Region",
    bytype: "By Type",
    top10Cities: "Top 10 Cities",
    top10CitiesTooltip: "Top 10 cities with most occurrences",
    intentionalHomicide: "Intentional Homicide",
    intentionalHomicideVictims: "Intentional Homicide Victims",
    trafficIntentionalHomicide: "Traffic Intentional Homicide",
    trafficIntentionalHomicideVictims: "Traffic Intentional Homicide Victims",
    trafficNegligentHomicide: "Traffic Negligent Homicide",
    otherNegligentHomicide: "Other Negligent Homicides",
    attemptedHomicide: "Attempted Homicide",
    bodilyInjuryWithDeath: "Bodily Injury Followed by Death",
    intentionalBodilyInjury: "Intentional Bodily Injury",
    trafficNegligentInjury: "Traffic Negligent Injury",
    crimeEvolutionByYear: "Crime Evolution by Year",
    crimeEvolutionTooltip: "Temporal evolution of recorded crimes",
    totalOf: "Total of",
    totalOccurrencesLastYears: "Total Occurrences Last Years",
    yearlyRecords: "Yearly Records",
    totalOccurrencesTooltip: "Total accumulated occurrences",
    distributionTooltip: "Distribution by category",
    localityData: "Locality Data",
    localityDataDescription: "Detailed analysis of occurrences by city and region",
    searchCityRegion: "Search city or region",
    byCity: "By City",
    region: "Region",
    occurrencesIn2024: "Occurrences in 2024",
    population: "Population",
    cityDetails: "City Details",
    recordedCrimes: "Recorded Crimes",
    bars: "Bars",
    lines: "Lines",
    pie: "Pie",
    rape: "Rape",
    homicide: "Homicide",
    regionDetails: "Region Details",
    regionRepresents: "The region represents",
    representsPercentage: "represents",
    ofTotalOccurrences: "of total occurrences",
    withTotal: "with total of",
    recordsIn2024: "records in 2024",
    cities: "cities",
    crimesByYear: "Crimes by Year",
    back: "Back",
    projectInfoSP: "Info SP Project",
    mappingAndAnalysis: "Intelligent mapping and analysis of occurrences in São Paulo",
    generalObjective: "General Objective",
    generalObjectiveDesc: "Develop an intelligent platform for monitoring and analysis of public safety data",
    technologiesAndFeatures: "Technologies and Features",
    geolocation: "Advanced geolocation",
    interactiveDashboards: "Interactive dashboards",
    temporalAnalysis: "Temporal analysis",
    predictiveAlgorithms: "Predictive algorithms",
    responsiveDesign: "Responsive design",
    specificObjectives: "Specific Objectives",
    collectData: "Collect security data",
    buildInterface: "Build intuitive interface",
    implementFilters: "Implement advanced filters",
    applyVisualization: "Apply visualization techniques",
    usePredictive: "Use predictive algorithms",
    projectTeam: "Project Team",
    teamDescription: "Project developed by Software Engineering students",
    advisor: "Advisor",
    developmentTeam: "Development Team",
    semester: "Semester",
    semesterValue: "2024/2",
    conclusion: "Conclusion",
    conclusionText: "Info SP represents an innovative solution for public safety data analysis, offering valuable insights for strategic decision making.",
    allDataFrom: "All data is from",
    securityDepartment: "Public Safety Department",
    copyright: "© 2024 Info SP. All rights reserved.",
    portuguese: "Portuguese",
    english: "English",
    spanish: "Spanish",
    // Occurrence types
    vehicleTheft: "Vehicle Theft",
    streetLightingIssue: "Street Lighting Issue",
    trafficAccident: "Traffic Accident",
    propertyInvasion: "Property Invasion",
    publicPropertyVandalism: "Public Property Vandalism",
    domesticViolence: "Domestic Violence",
    drugTrafficking: "Drug Trafficking",
    noisePollution: "Noise Pollution",
    publicPropertyDamage: "Public Property Damage",
    fraudAndScam: "Fraud and Scam",
    illegalConstruction: "Illegal Construction",
    waterLeakage: "Water Leakage",
    animalAbuse: "Animal Abuse",
    environmentalViolation: "Environmental Violation",
    publicTransportIssue: "Public Transport Issue",
    roadDamage: "Road Damage",
    garbageIssue: "Garbage Issue",
    sewerIssue: "Sewer Issue",
    publicSpaceOccupation: "Irregular Public Space Occupation",
    powerOutage: "Power Outage",
    internetOutage: "Internet Outage",
    publicHealthIssue: "Public Health Issue",
    educationIssue: "Education Issue",
    total: "Total"
  },
  es: {
    dashboard: "Panel de Control",
    reports: "Informes",
    regionalData: "Datos Regionales",
    about: "Acerca de",
    showingOf: "Mostrando",
    of: "de",
    occurrences: "ocurrencias",
    viewAll: "Ver Todos",
    typeId: "ID del Tipo",
    description: "Descripción",
    level: "Nivel",
    totalOccurrences: "Total de Ocurrencias",
    mostRecurringOccurrences: "Ocurrencias Más Recurrentes",
    mostFrequentTypes: "Tipos más frecuentes de ocurrencias",
    filter: "Filtrar",
    filterByLevel: "Filtrar por Nivel",
    critical: "Crítica",
    high: "Alta",
    medium: "Media",
    low: "Baja",
    referenceCode: "Código de Referencia",
    occurrencePercentage: "Esta ocurrencia representa",
    ofTotalRecorded: "del total registrado",
    downloadSpreadsheet: "Descargar Hoja de Cálculo",
    accessAndExport: "Acceda y exporte los datos del sistema",
    availableReports: "Informes Disponibles",
    accessSystemReports: "Acceda a los informes generados por el sistema",
    reportID: "ID del Informe",
    reportTitle: "Título del Informe",
    reportDate: "Fecha del Informe",
    reportType: "Tipo de Informe",
    reportStatus: "Estado del Informe",
    reportAction: "Acción",
    monthlyAnalysis: "Análisis Mensual de Ocurrencias",
    monthly: "Mensual",
    available: "Disponible",
    download: "Descargar",
    downloadStarted: "¡Descarga iniciada!",
    allOccurrences: "Todas las Ocurrencias",
    completeOccurrencesList: "Lista completa de todos los tipos de ocurrencias registradas en el sistema",
    backToDashboard: "Volver al Dashboard",
    dataTable: "Tabla de Datos",
    charts: "Gráficos",
    allOccurrenceTypes: "Todos los Tipos de Ocurrencias",
    detailedOccurrenceData: "Datos detallados de ocurrencias por año y tipo",
    distributionChart: "Gráfico de Distribución",
    evolutionChart: "Gráfico de Evolución",
    occurrenceDistribution: "Distribución de Ocurrencias",
    distributionByType: "Distribución porcentual por tipo de ocurrencia",
    yearlyEvolution: "Evolución Anual",
    evolutionOverYears: "Evolución de las ocurrencias a lo largo de los años",
    completeDetails: "Detalles Completos",
    viewCompleteDetails: "Ver Detalles Completos",
    numberOfThefts: "Número de Robos",
    theft: "Robo",
    numberOfRobberies: "Número de Atracos",
    robbery: "Atraco",
    dangerousCity: "Ciudad Peligrosa",
    safeCity: "Ciudad Segura",
    dangerousRegion: "Región Peligrosa",
    safeRegion: "Región Segura",
    distribution: "Distribución",
    byRegion: "Por Región",
    bytype: "Por Tipo",
    top10Cities: "Top 10 Ciudades",
    top10CitiesTooltip: "Las 10 ciudades con más ocurrencias",
    intentionalHomicide: "Homicidio Doloso",
    intentionalHomicideVictims: "Víctimas de Homicidio Doloso",
    trafficIntentionalHomicide: "Homicidio Doloso en Tráfico",
    trafficIntentionalHomicideVictims: "Víctimas de Homicidio Doloso en Tráfico",
    trafficNegligentHomicide: "Homicidio Culposo en Tráfico",
    otherNegligentHomicide: "Otros Homicidios Culposos",
    attemptedHomicide: "Intento de Homicidio",
    bodilyInjuryWithDeath: "Lesión Corporal Seguida de Muerte",
    intentionalBodilyInjury: "Lesión Corporal Dolosa",
    trafficNegligentInjury: "Lesión Corporal Culposa en Tráfico",
    crimeEvolutionByYear: "Evolución del Crimen por Año",
    crimeEvolutionTooltip: "Evolución temporal de los crímenes registrados",
    totalOf: "Total de",
    totalOccurrencesLastYears: "Total de Ocurrencias de los Últimos Años",
    yearlyRecords: "Registros Anuales",
    totalOccurrencesTooltip: "Total acumulado de ocurrencias",
    distributionTooltip: "Distribución por categoría",
    localityData: "Datos por Localidad",
    localityDataDescription: "Análisis detallado de las ocurrencias por ciudad y región",
    searchCityRegion: "Buscar ciudad o región",
    byCity: "Por Ciudad",
    region: "Región",
    occurrencesIn2024: "Ocurrencias en 2024",
    population: "Población",
    cityDetails: "Detalles de la Ciudad",
    recordedCrimes: "Crímenes Registrados",
    bars: "Barras",
    lines: "Líneas",
    pie: "Pastel",
    rape: "Violación",
    homicide: "Homicidio",
    regionDetails: "Detalles de la Región",
    regionRepresents: "La región representa",
    representsPercentage: "representa",
    ofTotalOccurrences: "del total de ocurrencias",
    withTotal: "con total de",
    recordsIn2024: "registros en 2024",
    cities: "ciudades",
    crimesByYear: "Crímenes por Año",
    back: "Volver",
    projectInfoSP: "Proyecto Info SP",
    mappingAndAnalysis: "Mapeo y análisis inteligente de ocurrencias en São Paulo",
    generalObjective: "Objetivo General",
    generalObjectiveDesc: "Desarrollar una plataforma inteligente para monitoreo y análisis de datos de seguridad pública",
    technologiesAndFeatures: "Tecnologías y Funcionalidades",
    geolocation: "Geolocalización avanzada",
    interactiveDashboards: "Dashboards interactivos",
    temporalAnalysis: "Análisis temporal",
    predictiveAlgorithms: "Algoritmos predictivos",
    responsiveDesign: "Diseño responsivo",
    specificObjectives: "Objetivos Específicos",
    collectData: "Recopilar datos de seguridad",
    buildInterface: "Construir interfaz intuitiva",
    implementFilters: "Implementar filtros avanzados",
    applyVisualization: "Aplicar técnicas de visualización",
    usePredictive: "Usar algoritmos predictivos",
    projectTeam: "Equipo del Proyecto",
    teamDescription: "Proyecto desarrollado por estudiantes de Ingeniería de Software",
    advisor: "Asesor",
    developmentTeam: "Equipo de Desarrollo",
    semester: "Semestre",
    semesterValue: "2024/2",
    conclusion: "Conclusión",
    conclusionText: "Info SP representa una solución innovadora para análisis de datos de seguridad pública, ofreciendo insights valiosos para toma de decisiones estratégicas.",
    allDataFrom: "Todos los datos provienen de la",
    securityDepartment: "Secretaría de Seguridad Pública",
    copyright: "© 2024 Info SP. Todos los derechos reservados.",
    portuguese: "Portugués",
    english: "Inglés",
    spanish: "Español",
    // Tipos de ocurrencias
    vehicleTheft: "Robo de Vehículo",
    streetLightingIssue: "Problema de Alumbrado Público",
    trafficAccident: "Accidente de Tráfico",
    propertyInvasion: "Invasión de Propiedad",
    publicPropertyVandalism: "Vandalismo en Propiedad Pública",
    domesticViolence: "Violencia Doméstica",
    drugTrafficking: "Tráfico de Drogas",
    noisePollution: "Contaminación Acústica",
    publicPropertyDamage: "Daño al Patrimonio Público",
    fraudAndScam: "Fraude y Estafa",
    illegalConstruction: "Construcción Ilegal",
    waterLeakage: "Fuga de Agua",
    animalAbuse: "Maltrato Animal",
    environmentalViolation: "Violación Ambiental",
    publicTransportIssue: "Problema en Transporte Público",
    roadDamage: "Daño en Vía Pública",
    garbageIssue: "Problema con Basura",
    sewerIssue: "Problema en Alcantarillado",
    publicSpaceOccupation: "Ocupación Irregular del Espacio Público",
    powerOutage: "Corte de Energía",
    internetOutage: "Falta de Internet",
    publicHealthIssue: "Problema de Salud Pública",
    educationIssue: "Problema en Educación",
    total: "Total"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState('pt');

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations['pt']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
