// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axdnoxxcxsyxpfhfebtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4ZG5veHhjeHN5eHBmaGZlYnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTcyNTksImV4cCI6MjA1ODk5MzI1OX0.l6R8loSX3PLPP1ZoRsJQvooAMv_ZZeXgHo9UP7uvZOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);